#contains configs shared in both environments

version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kurtis
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
    # gives name to mongo volume thats human readable vers rando nums and chars
      - mongo-db:/data/db

volumes:
  mongo-db: