#contains configs shared in both environments

version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app
  node-app:
    build: .
    image: kurtiveycodes/node-app
    # platform: linux/amd64   # Specify the platform for the image, used when on mac sometimes
    environment:
      - PORT=3000
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kurtis
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
    # gives name to mongo volume thats human readable vers rando nums and chars
      - mongo-db:/data/db
  redis:
    image: redis



volumes:
  mongo-db: